// services/contractsService.ts
import { ContratoUI, EstadisticasContratos } from "@/types/contract";

export async function obtenerEstadisticasContratos(): Promise<EstadisticasContratos> {
  await new Promise((r) => setTimeout(r, 300));
  return {
    activos: 1186,
    proxAVencer: 8,
    renovados: 234,
    vencidosAnulados: 45,
  };
}

export async function obtenerContratos(): Promise<ContratoUI[]> {
  await new Promise((r) => setTimeout(r, 500));
  return [
    {
      idContrato: 1,
      funcionario: { nombre: "Erik Vance", idContrato: "CN-8829", avatar: "EV" },
      tipoUI: "Término Fijo",
      area: "Finanzas",
      condiciones: "Contrato externo",
      tipo: "Externo",
      vigencia: "no_vigente",
      fechaInicio: "Oct 24, 2022",
      fechaFin: "Oct 24, 2023",
      estadoUI: "Vencido",
      validezTexto: "Vencido hace 1 día",
      validezPorcentaje: 100,
    },
    {
      idContrato: 2,
      funcionario: { nombre: "Diana Marsh", idContrato: "CN-1102", avatar: "DM" },
      tipoUI: "Término Fijo",
      area: "Operaciones",
      condiciones: "Contrato de seguridad",
      tipo: "Interno",
      vigencia: "no_vigente",
      fechaInicio: "Nov 02, 2022",
      fechaFin: "Nov 02, 2023",
      estadoUI: "Vencido",
      validezTexto: "Vence en 6 días",
      validezPorcentaje: 95,
    },
    {
      idContrato: 3,
      funcionario: { nombre: "James Holloway", idContrato: "CN-5541", avatar: "JH" },
      tipoUI: "Término Fijo",
      area: "Ingeniería",
      condiciones: "Contrato técnico",
      tipo: "Interno",
      vigencia: "vigente",
      fechaInicio: "Nov 11, 2022",
      fechaFin: "Nov 11, 2023",
      estadoUI: "Activo",
      validezTexto: "21 días restantes",
      validezPorcentaje: 70,
    },
    {
      idContrato: 4,
      funcionario: { nombre: "Alex Rivera", idContrato: "CN-9012", avatar: "AR" },
      tipoUI: "Término Indefinido",
      area: "Ingeniería",
      condiciones: "Contrato indefinido",
      tipo: "Interno",
      vigencia: "vigente",
      fechaInicio: "Ene 15, 2022",
      fechaFin: "-",
      estadoUI: "Activo",
      validezTexto: "En curso - Sin vencimiento",
      validezPorcentaje: 50,
    },
    {
      idContrato: 5,
      funcionario: { nombre: "Sofia Reyes", idContrato: "CN-7399", avatar: "SR" },
      tipoUI: "Término Fijo",
      area: "RRHH",
      condiciones: "Contrato estándar",
      tipo: "Interno",
      vigencia: "vigente",
      fechaInicio: "Mar 01, 2023",
      fechaFin: "Mar 01, 2024",
      estadoUI: "Activo",
      validezTexto: "168 días restantes",
      validezPorcentaje: 40,
    },
    {
      idContrato: 6,
      funcionario: { nombre: "Laura Chen", idContrato: "CN-3362", avatar: "LC" },
      tipoUI: "Servicio",
      area: "Analítica",
      condiciones: "Contrato de servicio",
      tipo: "Externo",
      vigencia: "vigente",
      fechaInicio: "Ene 01, 2023",
      fechaFin: "Dic 31, 2023",
      estadoUI: "Activo",
      validezTexto: "10 días restantes",
      validezPorcentaje: 85,
    },
    {
      idContrato: 7,
      funcionario: { nombre: "Robert Kim", idContrato: "DN-7841", avatar: "RK" },
      tipoUI: "Término Fijo",
      area: "Legal",
      condiciones: "Contrato renovado",
      tipo: "Interno",
      vigencia: "vigente",
      fechaInicio: "Feb 01, 2022",
      fechaFin: "Feb 01, 2023",
      estadoUI: "Renovado",
      validezTexto: "Renovado Ene 28, 2023",
      validezPorcentaje: 60,
    },
    {
      idContrato: 8,
      funcionario: { nombre: "Anna Brooks", idContrato: "CN-6503", avatar: "AB" },
      tipoUI: "Pasantía",
      area: "Finanzas",
      condiciones: "Contrato pasantía",
      tipo: "Externo",
      vigencia: "no_vigente",
      fechaInicio: "Jun 01, 2023",
      fechaFin: "Ago 31, 2023",
      estadoUI: "Anulado",
      validezTexto: "Anulado Ago 15, 2023",
      validezPorcentaje: 100,
    },
  ];
}